server:
  port: 8080
eureka:
  client:
    register-with-eureka: false # 实例是否在eureka服务器上注册自己的信息以供其他服务发现，默认为true
    fetch-registry: true # 此客户端是否获取eureka服务器注册表上的注册信息，默认为true
    service-url:
        defaultZone: http://localhost:8761/eureka/
#  instance:
#    metadata-map:
#      management:
#        pore: ${management.server.port:8081}
turbine:
  aggregator:
    cluster-config: DEMO
  app-config: user-server,order-server
  cluster-name-expression: metadata['demo']
#management:
#  endpoints:
#    web:
#      exposure:
#        include: '*'