server:
  port: 8001
spring:
  application:
    name: user-server
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.99.144.63/user
    username: root
    password: 123456
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka
mybatis-plus:
  global-config:
    db-config:
      update-strategy: not_empty