server:
  port: 8080
spring:
  application:
    name: web
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka
feign:
  hystrix:
    enabled: true # 启用断路器
  httpclient:
#    connection-timeout: 3000
#    connection-timer-repeat: 1000
management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream # 开启hystrix监控


