server:
  port: 1000
spring:
  application:
    name: web
  cloud:
    loadbalancer:
      ribbon:
        enabled: true # Spring Cloud Netflix Ribbon is now in maintenance mode,using Spring Cloud LoadBalancer instead
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka
# 开启监控
management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream
# 启用断路器
feign:
  hystrix:
    enabled: true
###配置请求超时时间
hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: true #执行是否启用超时，默认启用true
        isolation:
          thread:
            timeoutInMilliseconds: 6000
ribbon:
  ReadTimeout: 2000 #请求处理的超时时间
  ConnectTimeout: 800 #请求连接的超时时间
  MaxAutoRetries: 0 #同一台实例最大重试次数,不包括首次调用
  MaxAutoRetriesNextServer: 0 #重试负载均衡其他的实例最大重试次数,不包括首次调用
  OkToRetryOnAllOperations: false #是否所有操作都重试
